### Get All Users
GET http://localhost:10000/users
### Get Single User
GET http://localhost:10000/users/63dd2feb935397b9893ab538

### Get All Vehicles
GET http://localhost:10000/vehicles
### Get Single Vehicle
GET http://localhost:10000/vehicles/63dd27a0ad81f37548efa9f8

### Create New LocalHost user
POST http://localhost:10000/users/ HTTP/1.1 
content-type: application/json

{"firstName":"James", "lastName":"Bond", "username":"jbondy", "password":"bluepass", "hoursRemaining":5}


### Create New LocalHost Vehicles
POST http://localhost:10000/vehicles/ HTTP/1.1 
content-type: application/json

{"year":"2022", "make":"Chevrolet", "model":"bolt", "mileage":20000, "remainingRange":120, "currentlyRented": false, "broken": false}


### Update Existing LocalHost User
PUT http://localhost:10000/users/63ee5fb5a8b8afa925ac657b HTTP/1.1 
content-type: application/json

{"firstName":"James", "lastName":"Bond", "username":"jbondy", "password":"bluepass", "hoursRemaining":5}

### Delete LocalHost User
DELETE http://localhost:10000/users/63dd2a070a417a7e957aba61 HTTP/1.1

### Update Existing LocalHost Vehicle
PUT http://localhost:10000/vehicles/63def93567eaa323d0cc5eeb HTTP/1.1 
content-type: application/json

{"year":"2022", "make":"Chevrolet", "model":"bolt", "mileage":20000, "remainingRange":120, "currentlyRented": false, "broken": false}

### Delete LocalHost Vehicle
DELETE http://localhost:10000/vehicles/63def93267eaa323d0cc5eea HTTP/1.1






### Get All Users Render
GET https://carrentalapp.onrender.com/users
### Get Single User Render
GET https://carrentalapp.onrender.com/users/63dd2feb935397b9893ab538

### Get All Vehicles Render
GET https://carrentalapp.onrender.com/vehicles
### Get Single Vehicle Render
GET https://carrentalapp.onrender.com/vehicles/63dd27a0ad81f37548efa9f8

### Create New user Render
POST https://carrentalapp.onrender.com/users/ HTTP/1.1 
content-type: application/json

{"firstName":"James", "lastName":"Bond", "username":"jbondy", "password":"bluepass", "hoursRemaining":5}


### Create New Vehicle Render
POST https://carrentalapp.onrender.com/vehicles/ HTTP/1.1 
content-type: application/json

{"year":"2022", "make":"Chevrolet", "model":"bolt", "mileage":20000, "remainingRange":120, "currentlyRented": false, "broken": false}

### Update Existing Render User
PUT https://carrentalapp.onrender.com/users/63def8f667eaa323d0cc5ee9 HTTP/1.1 
content-type: application/json

{"firstName":"James", "lastName":"Bond", "username":"jbondy", "password":"bluepass", "hoursRemaining":5}

### Delete Render User
DELETE https://carrentalapp.onrender.com/users/63dd2a070a417a7e957aba61 HTTP/1.1

### Update Existing Render Vehicle
PUT https://carrentalapp.onrender.com/vehicles/63def93567eaa323d0cc5eeb HTTP/1.1 
content-type: application/json

{"year":"2022", "make":"Chevrolet", "model":"bolt", "mileage":20000, "remainingRange":120, "currentlyRented": false, "broken": false}

### Delete Render Vehicle
DELETE https://carrentalapp.onrender.com/vehicles/63dd27a0ad81f37548efa9f8 HTTP/1.1



